### ISSUE TITLE
How can I integrated rush with 'lint-staged' package?

### ISSUE THREAD

**Issue by cqcmdwym** [Microsoft/rush-example#10]
Since there is no package.json file in the root folder. I have to install the 'lint-staged' package into all the projects.

**Comment by fedemp** [comment]
I'm just starting with Rush, but for `lint-staged` I followed the steps in https://rushjs.io/pages/maintainer/enabling_prettier/ i.e. creating an autoinstaller called lint-staged but inside it, I installed `lint-staged` and everything it needs (like `eslint`). I defined the command `rush lint-staged`. The same guide shows how to create a precommit hook, so there I just call `lint-staged`.

my precommit hook:
```
node common/scripts/install-run-rush.js lint-staged || exit $?
```

**Comment by cqcmdwym** [comment]
> I'm just starting with Rush, but for `lint-staged` I followed the steps in https://rushjs.io/pages/maintainer/enabling_prettier/ i.e. creating an autoinstaller called lint-staged but inside it, I installed `lint-staged` and everything it needs (like `eslint`). I defined the command `rush lint-staged`. The same guide shows how to create a precommit hook, so there I just call `lint-staged`.
> 
> my precommit hook:
> 
> ```
> node common/scripts/install-run-rush.js lint-staged || exit $?
> ```

Have you changed the package.json file in sub-projects?

**Comment by fedemp** [comment]
Not for lint-staged, but right now I'm moving the .eslintrc.js to the root of each project since it seems it's the recommended approach.

Just followed the instructions. I used the name `rush-husky` cause I though I would need `husky`:

`rush init-autoinstaller --name rush-husky`

and then my `package.json`

```json
{
  "name": "rush-husky",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@typescript-eslint/eslint-plugin": "^3.10.1",
    "@typescript-eslint/parser": "^3.10.1",
    "eslint": "~7.7.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.20.6",
    "lint-staged": "^10.2.13",
    "prettier": "~2.1.0",
    "stylelint": "~13.6.1",
    "stylelint-config-prettier": "^8.0.1",
    "stylelint-config-recommended": "^3.0.0",
    "stylelint-scss": "3.18.0",
    "typescript": "~4.0.2"
  }
}
```

In `common/config/rush/command-line.json`

```json
    {
      "name": "lint-staged",
      "commandKind": "global",
      "summary": "Used by the pre-commit Git hook. This command invokes lint-staged to reformat staged changes.",

      "autoinstallerName": "rush-husky",

      "shellCommand": "lint-staged"
    },
```

In `common/git-hooks/pre-commit`

```sh
#!/bin/sh
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

# Invoke the "rush lint-staged" custom command to reformat files whenever they
# are committed. The command is defined in common/config/rush/command-line.json
# and uses the "rush-prettier" autoinstaller.
node common/scripts/install-run-rush.js lint-staged || exit $?
```

And my `.lintstagedrc` at the root of the Rush repo

```json
{
  "*.{ts,tsx}": "eslint --cache --fix",
  "*.{css,scss}": "stylelint --fix",
  "*.{ts,tsx,css,scss,md}": "prettier --write"
}
```

**Comment by cqcmdwym** [comment]
`package.json` is in the root folder of your project or sub-project? It seems that there is no `package.json` in root folder of rush repo

**Comment by fedemp** [comment]
The package.json I mentioned is in `common/autoinstallers/rush-husky/`.

`rush-husky` is the name I chose for my autoinstaller.

**Comment by ycnmhd** [comment]
@fedemp did you get it to work with vscode-eslint extension?

**Comment by leohxj** [comment]
I recommend read this article:
[Build a scalable front-end with Rush monorepo and React — Part 3 | by Alexandru Bereghici | ITNEXT](https://itnext.io/build-a-scalable-front-end-with-rush-monorepo-and-react-part-3-b90430f15af7)

each project has its lint-staged.only prettier/commitlint in the root.

**Comment by octogonz** [comment]
We recommend not to use Husky with Rush, because it modifies the Git configuration for your working directory (to look for hooks in `.husky` instead of the standard `.git/hooks` folder). This modification is sticky, for example it will persist even if you checkout a different branch that is not using Husky, which can result in unintended effects.

Rush already has its own built-in feature for installing Git hooks, documented here: https://rushjs.io/pages/maintainer/git_hooks/

**Comment by octogonz** [comment]
> Since there is no package.json file in the root folder. I have to install the 'lint-staged' package into all the projects.

It is okay to use `lint-staged` in a Rush repo if your commit hook needs to do more than simply invoking Prettier.  (We don't apply ESLint via a Git hook, see [this note](https://rushjs.io/pages/maintainer/enabling_prettier/) for details, so we chose the simpler `pretty-quick` package. But `lint-staged` is okay, too.)

It is not necessary to add `lint-staged` as a dependency of every project. Instead, the recommended practice would be to create an autoinstaller folder with the **package.json** dependencies needed for **lint-staged**, similar to how Prettier is configured in that article.

**Comment by AaronConlon** [comment]
@octogonz I still don't know how to use git commitlint in a rushjs project...Can you give me some suggestions?Thanks.
