### ISSUE TITLE
ERROR: running in node 18.12 environment 

### ISSUE THREAD

**Issue by xuewan-seven** [Microsoft/rush-example#17]
ERROR: Your dev environment is running Node.js version v18.12.1 which does not meet the requirements for building this repository.  (The rush.json configuration requires nodeSupportedVersionRange=">=12.13.0 <13.0.0 || >=14.15.0
<15.0.0 || >=16.13.0 <17.0.0")

**Comment by octogonz** [comment]
@xuewan-seven This is configurable using the [nodeSupportedVersionRange](https://rushjs.io/pages/configs/rush_json/) setting in **rush.json.**

This repo is generated from the `rush init` template, and it looks like the template has not been updated to include the latest LTS series.  

Thanks for reporting this!

**Comment by octogonz** [comment]
[2022-10-25](https://github.com/nodejs/Release) is when 18.x became LTS

**Comment by octogonz** [comment]
I created a PR https://github.com/microsoft/rushstack/pull/3940

**Comment by octogonz** [comment]
Fixed by https://github.com/microsoft/rushstack/pull/4278
