### ISSUE TITLE
Rush Change

### ISSUE THREAD

**Issue by RiChrisMurphy** [Microsoft/rush-example#8]
I can't seem to get rush change working, but I'm also not sure if I'm doing it properly. I always get "No changes were detected to relevant packages on this branch. Nothing to do." If there is an example for how change operates. I'd appreciate taking a look.

**Comment by RiChrisMurphy** [comment]
actually solved it

**Comment by fedemp** [comment]
For the record, OP probably added `"shouldPublish": true` to the project in `rush.json`.
